huh_encore:
  js_entries:
    - { name: "contao-rootnav-bundle", requires_css: false, head: false, file: "vendor/heimrichhannot/contao-rootnav-bundle/src/Resources/public/js/contao-rootnav-bundle.es6.js"}
  unset_global_keys:
    js:
      - huh_rootnav