services:
  huh.rootnav.listener.callback:
    class: HeimrichHannot\RootnavBundle\EventListener\CallbackListener
    arguments:
      - '@contao.framework'
      - '%contao.url_suffix%'

  HeimrichHannot\RootnavBundle\Command\MigrationCommand:
    autowire: true
    autoconfigure: true

  HeimrichHannot\RootnavBundle\Asset\EncoreExtension:
    autoconfigure: true
